export const dogIdName = {
  1: "Affenpinscher",
  2: "Afghan Hound",
  3: "African Hunting Dog",
  4: "Airedale Terrier",
  5: "Akbash Dog",
  6: "Akita",
  7: "Alapaha Blue Blood Bulldog",
  8: "Alaskan Husky",
  9: "Alaskan Malamute",
  10: "American Bulldog",
  11: "American Bully",
  12: "American Eskimo Dog",
  13: "American Eskimo Dog (Miniature)",
  14: "American Foxhound",
  15: "American Pit Bull Terrier",
  16: "American Staffordshire Terrier",
  17: "American Water Spaniel",
  18: "Anatolian Shepherd Dog",
  19: "Appenzeller Sennenhund",
  21: "Australian Cattle Dog",
  22: "Australian Kelpie",
  23: "Australian Shepherd",
  24: "Australian Terrier",
  25: "Azawakh",
  26: "Barbet",
  28: "Basenji",
  29: "Basset Bleu de Gascogne",
  30: "Basset Hound",
  31: "Beagle",
  32: "Bearded Collie",
  33: "Beauceron",
  34: "Bedlington Terrier",
  36: "Belgian Malinois",
  38: "Belgian Tervuren",
  41: "Bernese Mountain Dog",
  42: "Bichon Frise",
  43: "Black and Tan Coonhound",
  45: "Bloodhound",
  47: "Bluetick Coonhound",
  48: "Boerboel",
  50: "Border Collie",
  51: "Border Terrier",
  53: "Boston Terrier",
  54: "Bouvier des Flandres",
  55: "Boxer",
  56: "Boykin Spaniel",
  57: "Bracco Italiano",
  58: "Briard",
  59: "Brittany",
  61: "Bull Terrier",
  62: "Bull Terrier (Miniature)",
  64: "Bullmastiff",
  65: "Cairn Terrier",
  67: "Cane Corso",
  68: "Cardigan Welsh Corgi",
  69: "Catahoula Leopard Dog",
  70: "Caucasian Shepherd (Ovcharka)",
  71: "Cavalier King Charles Spaniel",
  76: "Chesapeake Bay Retriever",
  78: "Chinese Crested",
  79: "Chinese Shar-Pei",
  80: "Chinook",
  81: "Chow Chow",
  84: "Clumber Spaniel",
  86: "Cocker Spaniel",
  87: "Cocker Spaniel (American)",
  89: "Coton de Tulear",
  92: "Dalmatian",
  94: "Doberman Pinscher",
  95: "Dogo Argentino",
  98: "Dutch Shepherd",
  101: "English Setter",
  102: "English Shepherd",
  103: "English Springer Spaniel",
  104: "English Toy Spaniel",
  105: "English Toy Terrier",
  107: "Eurasier",
  108: "Field Spaniel",
  110: "Finnish Lapphund",
  111: "Finnish Spitz",
  113: "French Bulldog",
  114: "German Pinscher",
  115: "German Shepherd Dog",
  116: "German Shorthaired Pointer",
  119: "Giant Schnauzer",
  120: "Glen of Imaal Terrier",
  121: "Golden Retriever",
  123: "Gordon Setter",
  124: "Great Dane",
  125: "Great Pyrenees",
  127: "Greyhound",
  128: "Griffon Bruxellois",
  129: "Harrier",
  130: "Havanese",
  134: "Irish Setter",
  135: "Irish Terrier",
  137: "Irish Wolfhound",
  138: "Italian Greyhound",
  140: "Japanese Chin",
  141: "Japanese Spitz",
  142: "Keeshond",
  144: "Komondor",
  145: "Kooikerhondje",
  147: "Kuvasz",
  149: "Labrador Retriever",
  151: "Lagotto Romagnolo",
  153: "Lancashire Heeler",
  155: "Leonberger",
  156: "Lhasa Apso",
  161: "Maltese",
  165: "Miniature American Shepherd",
  167: "Miniature Pinscher",
  168: "Miniature Schnauzer",
  171: "Newfoundland",
  172: "Norfolk Terrier",
  176: "Norwich Terrier",
  177: "Nova Scotia Duck Tolling Retriever",
  178: "Old English Sheepdog",
  179: "Olde English Bulldogge",
  181: "Papillon",
  183: "Pekingese",
  184: "Pembroke Welsh Corgi",
  185: "Perro de Presa Canario",
  188: "Pharaoh Hound",
  189: "Plott",
  193: "Pomeranian",
  196: "Poodle (Miniature)",
  197: "Poodle (Toy)",
  201: "Pug",
  204: "Puli",
  205: "Pumi",
  207: "Rat Terrier",
  208: "Redbone Coonhound",
  209: "Rhodesian Ridgeback",
  210: "Rottweiler",
  211: "Russian Toy",
  212: "Saint Bernard",
  213: "Saluki",
  214: "Samoyed",
  216: "Schipperke",
  218: "Scottish Deerhound",
  219: "Scottish Terrier",
  221: "Shetland Sheepdog",
  222: "Shiba Inu",
  223: "Shih Tzu",
  225: "Shiloh Shepherd",
  226: "Siberian Husky",
  228: "Silky Terrier",
  232: "Smooth Fox Terrier",
  233: "Soft Coated Wheaten Terrier",
  235: "Spanish Water Dog",
  236: "Spinone Italiano",
  238: "Staffordshire Bull Terrier",
  239: "Standard Schnauzer",
  242: "Swedish Vallhund",
  243: "Thai Ridgeback",
  244: "Tibetan Mastiff",
  245: "Tibetan Spaniel",
  246: "Tibetan Terrier",
  248: "Toy Fox Terrier",
  250: "Treeing Walker Coonhound",
  251: "Vizsla",
  253: "Weimaraner",
  254: "Welsh Springer Spaniel",
  256: "West Highland White Terrier",
  257: "Whippet",
  258: "White Shepherd",
  259: "Wire Fox Terrier",
  260: "Wirehaired Pointing Griffon",
  261: "Wirehaired Vizsla",
  262: "Xoloitzcuintli",
  264: "Yorkshire Terrier",
};

export const dogNameId = {
  Affenpinscher: 1,
  "Afghan Hound": 2,
  "African Hunting Dog": 3,
  "Airedale Terrier": 4,
  "Akbash Dog": 5,
  Akita: 6,
  "Alapaha Blue Blood Bulldog": 7,
  "Alaskan Husky": 8,
  "Alaskan Malamute": 9,
  "American Bulldog": 10,
  "American Bully": 11,
  "American Eskimo Dog": 12,
  "American Eskimo Dog (Miniature)": 13,
  "American Foxhound": 14,
  "American Pit Bull Terrier": 15,
  "American Staffordshire Terrier": 16,
  "American Water Spaniel": 17,
  "Anatolian Shepherd Dog": 18,
  "Appenzeller Sennenhund": 19,
  "Australian Cattle Dog": 21,
  "Australian Kelpie": 22,
  "Australian Shepherd": 23,
  "Australian Terrier": 24,
  Azawakh: 25,
  Barbet: 26,
  Basenji: 28,
  "Basset Bleu de Gascogne": 29,
  "Basset Hound": 30,
  Beagle: 31,
  "Bearded Collie": 32,
  Beauceron: 33,
  "Bedlington Terrier": 34,
  "Belgian Malinois": 36,
  "Belgian Tervuren": 38,
  "Bernese Mountain Dog": 41,
  "Bichon Frise": 42,
  "Black and Tan Coonhound": 43,
  Bloodhound: 45,
  "Bluetick Coonhound": 47,
  Boerboel: 48,
  "Border Collie": 50,
  "Border Terrier": 51,
  "Boston Terrier": 53,
  "Bouvier des Flandres": 54,
  Boxer: 55,
  "Boykin Spaniel": 56,
  "Bracco Italiano": 57,
  Briard: 58,
  Brittany: 59,
  "Bull Terrier": 61,
  "Bull Terrier (Miniature)": 62,
  Bullmastiff: 64,
  "Cairn Terrier": 65,
  "Cane Corso": 67,
  "Cardigan Welsh Corgi": 68,
  "Catahoula Leopard Dog": 69,
  "Caucasian Shepherd (Ovcharka)": 70,
  "Cavalier King Charles Spaniel": 71,
  "Chesapeake Bay Retriever": 76,
  "Chinese Crested": 78,
  "Chinese Shar-Pei": 79,
  Chinook: 80,
  "Chow Chow": 81,
  "Clumber Spaniel": 84,
  "Cocker Spaniel": 86,
  "Cocker Spaniel (American)": 87,
  "Coton de Tulear": 89,
  Dalmatian: 92,
  "Doberman Pinscher": 94,
  "Dogo Argentino": 95,
  "Dutch Shepherd": 98,
  "English Setter": 101,
  "English Shepherd": 102,
  "English Springer Spaniel": 103,
  "English Toy Spaniel": 104,
  "English Toy Terrier": 105,
  Eurasier: 107,
  "Field Spaniel": 108,
  "Finnish Lapphund": 110,
  "Finnish Spitz": 111,
  "French Bulldog": 113,
  "German Pinscher": 114,
  "German Shepherd Dog": 115,
  "German Shorthaired Pointer": 116,
  "Giant Schnauzer": 119,
  "Glen of Imaal Terrier": 120,
  "Golden Retriever": 121,
  "Gordon Setter": 123,
  "Great Dane": 124,
  "Great Pyrenees": 125,
  Greyhound: 127,
  "Griffon Bruxellois": 128,
  Harrier: 129,
  Havanese: 130,
  "Irish Setter": 134,
  "Irish Terrier": 135,
  "Irish Wolfhound": 137,
  "Italian Greyhound": 138,
  "Japanese Chin": 140,
  "Japanese Spitz": 141,
  Keeshond: 142,
  Komondor: 144,
  Kooikerhondje: 145,
  Kuvasz: 147,
  "Labrador Retriever": 149,
  "Lagotto Romagnolo": 151,
  "Lancashire Heeler": 153,
  Leonberger: 155,
  "Lhasa Apso": 156,
  Maltese: 161,
  "Miniature American Shepherd": 165,
  "Miniature Pinscher": 167,
  "Miniature Schnauzer": 168,
  Newfoundland: 171,
  "Norfolk Terrier": 172,
  "Norwich Terrier": 176,
  "Nova Scotia Duck Tolling Retriever": 177,
  "Old English Sheepdog": 178,
  "Olde English Bulldogge": 179,
  Papillon: 181,
  Pekingese: 183,
  "Pembroke Welsh Corgi": 184,
  "Perro de Presa Canario": 185,
  "Pharaoh Hound": 188,
  Plott: 189,
  Pomeranian: 193,
  "Poodle (Miniature)": 196,
  "Poodle (Toy)": 197,
  Pug: 201,
  Puli: 204,
  Pumi: 205,
  "Rat Terrier": 207,
  "Redbone Coonhound": 208,
  "Rhodesian Ridgeback": 209,
  Rottweiler: 210,
  "Russian Toy": 211,
  "Saint Bernard": 212,
  Saluki: 213,
  Samoyed: 214,
  Schipperke: 216,
  "Scottish Deerhound": 218,
  "Scottish Terrier": 219,
  "Shetland Sheepdog": 221,
  "Shiba Inu": 222,
  "Shih Tzu": 223,
  "Shiloh Shepherd": 225,
  "Siberian Husky": 226,
  "Silky Terrier": 228,
  "Smooth Fox Terrier": 232,
  "Soft Coated Wheaten Terrier": 233,
  "Spanish Water Dog": 235,
  "Spinone Italiano": 236,
  "Staffordshire Bull Terrier": 238,
  "Standard Schnauzer": 239,
  "Swedish Vallhund": 242,
  "Thai Ridgeback": 243,
  "Tibetan Mastiff": 244,
  "Tibetan Spaniel": 245,
  "Tibetan Terrier": 246,
  "Toy Fox Terrier": 248,
  "Treeing Walker Coonhound": 250,
  Vizsla: 251,
  Weimaraner: 253,
  "Welsh Springer Spaniel": 254,
  "West Highland White Terrier": 256,
  Whippet: 257,
  "White Shepherd": 258,
  "Wire Fox Terrier": 259,
  "Wirehaired Pointing Griffon": 260,
  "Wirehaired Vizsla": 261,
  Xoloitzcuintli: 262,
  "Yorkshire Terrier": 264,
};

export const dogNameE = {
  Affenpinscher: "아펜핀셔",
  "Afghan Hound": "아프간 하운드",
  "African Hunting Dog": "아프리카 사냥개",
  "Airedale Terrier": "에어데일 테리어",
  "Akbash Dog": "아크바시 독",
  Akita: "아키타",
  "Alapaha Blue Blood Bulldog": "알라파 블루 블러드 불독",
  "Alaskan Husky": "알래스카 허스키",
  "Alaskan Malamute": "알래스카 말라뮤트",
  "American Bulldog": "아메리칸 불독",
  "American Bully": "아메리칸 불리",
  "American Eskimo Dog": "아메리칸 에스키모 독",
  "American Eskimo Dog (Miniature)": "아메리칸 에스키모 독 (미니어처)",
  "American Foxhound": "아메리칸 폭스하운드",
  "American Pit Bull Terrier": "아메리칸 핏불 테리어",
  "American Staffordshire Terrier": "아메리칸 스태퍼드셔 테리어",
  "American Water Spaniel": "아메리칸 워터 스패니얼",
  "Anatolian Shepherd Dog": "아나톨리아 목장개",
  "Appenzeller Sennenhund": "아펜젤러 션넨훈트",
  "Australian Cattle Dog": "오스트레일리안 캐틀 독",
  "Australian Kelpie": "오스트레일리안 켈피",
  "Australian Shepherd": "오스트레일리안 셰퍼드",
  "Australian Terrier": "오스트레일리안 테리어",
  Azawakh: "아자왁",
  Barbet: "바르베",
  Basenji: "바센지",
  "Basset Bleu de Gascogne": "바세 블루 드 가스코뉴",
  "Basset Hound": "바셋 하운드",
  Beagle: "비글",
  "Bearded Collie": "비어디드 콜리",
  Beauceron: "보시롱",
  "Bedlington Terrier": "베들링턴 테리어",
  "Belgian Malinois": "벨기에 말리노이즈",
  "Belgian Tervuren": "벨기에 터뷰런",
  "Bernese Mountain Dog": "버니즈 마운틴 독",
  "Bichon Frise": "비숑 프리제",
  "Black and Tan Coonhound": "블랙 앤 탄 쿤하운드",
  Bloodhound: "블러드하운드",
  "Bluetick Coonhound": "블루틱 쿤하운드",
  Boerboel: "보어불",
  "Border Collie": "보더 콜리",
  "Border Terrier": "보더 테리어",
  "Boston Terrier": "보스턴 테리어",
  "Bouvier des Flandres": "부비에 데 플랑드르",
  Boxer: "복서",
  "Boykin Spaniel": "보이킨 스패니얼",
  "Bracco Italiano": "이탈리안 포인터",
  Briard: "브리아드",
  Brittany: "브리트니",
  "Bull Terrier": "불 테리어",
  "Bull Terrier (Miniature)": "불 테리어 (미니어처)",
  Bullmastiff: "불마스티프",
  "Cairn Terrier": "케언 테리어",
  "Cane Corso": "카네 코르소",
  "Cardigan Welsh Corgi": "카디건 웰시 코기",
  "Catahoula Leopard Dog": "카타훌라 레오파드 독",
  "Caucasian Shepherd (Ovcharka)": "코카시안 셰퍼드 (오브차르카)",
  "Cavalier King Charles Spaniel": "카발리에 킹 찰스 스패니얼",
  "Chesapeake Bay Retriever": "체사피크 베이 리트리버",
  "Chinese Crested": "차이니스 크레스티드",
  "Chinese Shar-Pei": "차이니스 샤페이",
  Chinook: "치눅",
  "Chow Chow": "차우 차우",
  "Clumber Spaniel": "클럼버 스패니얼",
  "Cocker Spaniel": "코커 스패니얼",
  "Cocker Spaniel (American)": "코커 스패니얼 (아메리칸)",
  "Coton de Tulear": "코튼 드 뚤레아",
  Dalmatian: "달마티안",
  "Doberman Pinscher": "도베르만 핀셔",
  "Dogo Argentino": "도고 아르헨티노",
  "Dutch Shepherd": "더치 셰퍼드",
  "English Setter": "잉글리쉬 세터",
  "English Shepherd": "잉글리쉬 셰퍼드",
  "English Springer Spaniel": "잉글리쉬 스프링어 스패니얼",
  "English Toy Spaniel": "잉글리쉬 토이 스패니얼",
  "English Toy Terrier": "잉글리쉬 토이 테리어",
  Eurasier: "유라시안",
  "Field Spaniel": "필드 스패니얼",
  "Finnish Lapphund": "핀란드 랩훈드",
  "Finnish Spitz": "핀란드 스피츠",
  "French Bulldog": "프렌치 불독",
  "German Pinscher": "저먼 핀셔",
  "German Shepherd Dog": "저먼 셰퍼드 독",
  "German Shorthaired Pointer": "저먼 숏헤어 포인터",
  "Giant Schnauzer": "자이언트 슈나우저",
  "Glen of Imaal Terrier": "글렌 오브 이말 테리어",
  "Golden Retriever": "골든 리트리버",
  "Gordon Setter": "고든 세터",
  "Great Dane": "그레이트 데인",
  "Great Pyrenees": "그레이트 피레니즈",
  Greyhound: "그레이하운드",
  "Griffon Bruxellois": "브뤼셀 그리폰",
  Harrier: "해리어",
  Havanese: "하바니즈",
  "Irish Setter": "아이리시 세터",
  "Irish Terrier": "아이리시 테리어",
  "Irish Wolfhound": "아이리시 울프하운드",
  "Italian Greyhound": "이탈리안 그레이하운드",
  "Japanese Chin": "재패니스 친",
  "Japanese Spitz": "재패니스 스피츠",
  Keeshond: "키스혼드",
  Komondor: "코몬도르",
  Kooikerhondje: "쿠키어혼치",
  Kuvasz: "쿠바스",
  "Labrador Retriever": "라브라도 리트리버",
  "Lagotto Romagnolo": "라고토 로마뇰로",
  "Lancashire Heeler": "랭카셔 힐러",
  Leonberger: "레온베르거",
  "Lhasa Apso": "라사 압소",
  Maltese: "말티즈",
  "Miniature American Shepherd": "미니어처 아메리칸 셰퍼드",
  "Miniature Pinscher": "미니어처 핀셔",
  "Miniature Schnauzer": "미니어처 슈나우저",
  Newfoundland: "뉴펀들랜드",
  "Norfolk Terrier": "노퍽 테리어",
  "Norwich Terrier": "노리치 테리어",
  "Nova Scotia Duck Tolling Retriever": "노바 스코샤 덕 톨링 리트리버",
  "Old English Sheepdog": "올드 잉글리쉬 쉽독",
  "Olde English Bulldogge": "올드 잉글리쉬 불독",
  Papillon: "파피용",
  Pekingese: "페키니즈",
  "Pembroke Welsh Corgi": "펨브록 웰시 코기",
  "Perro de Presa Canario": "페로 데 프레사 카나리오",
  "Pharaoh Hound": "파라오 하운드",
  Plott: "플롯트",
  Pomeranian: "포메라니안",
  "Poodle (Miniature)": "푸들 (미니어처)",
  "Poodle (Toy)": "푸들 (토이)",
  Pug: "퍼그",
  Puli: "푸리",
  Pumi: "푸미",
  "Rat Terrier": "랫 테리어",
  "Redbone Coonhound": "레드본 쿤하운드",
  "Rhodesian Ridgeback": "로데시안 루지백",
  Rottweiler: "로트와일러",
  "Russian Toy": "러시안 토이",
  "Saint Bernard": "세인트 버나드",
  Saluki: "살루키",
  Samoyed: "사모예드",
  Schipperke: "슈퍼크",
  "Scottish Deerhound": "스코티시 디어하운드",
  "Scottish Terrier": "스코티시 테리어",
  "Shetland Sheepdog": "셰틀랜드 쉽독",
  "Shiba Inu": "시바 이누",
  "Shih Tzu": "시쯔",
  "Shiloh Shepherd": "시로 셰퍼드",
  "Siberian Husky": "시베리안 허스키",
  "Silky Terrier": "실키 테리어",
  "Smooth Fox Terrier": "스무스 폭스 테리어",
  "Soft Coated Wheaten Terrier": "소프트 코티드 휘튼 테리어",
  "Spanish Water Dog": "스페인 워터 독",
  "Spinone Italiano": "스피노네 이탈리아노",
  "Staffordshire Bull Terrier": "스태퍼드셔 불 테리어",
  "Standard Schnauzer": "스탠더드 슈나우저",
  "Swedish Vallhund": "스웨디시 발훈드",
  "Thai Ridgeback": "타이 리지백",
  "Tibetan Mastiff": "티베탄 매스티프",
  "Tibetan Spaniel": "티베탄 스패니얼",
  "Tibetan Terrier": "티베탄 테리어",
  "Toy Fox Terrier": "토이 폭스 테리어",
  "Treeing Walker Coonhound": "트리잉 워커 쿤하운드",
  Vizsla: "비즐라",
  Weimaraner: "와이마라너",
  "Welsh Springer Spaniel": "웰시 스프링어 스패니얼",
  "West Highland White Terrier": "웨스트 하이랜드 화이트 테리어",
  Whippet: "위펫",
  "White Shepherd": "화이트 셰퍼드",
  "Wire Fox Terrier": "와이어 폭스 테리어",
  "Wirehaired Pointing Griffon": "와이어헤어드 포인팅 그리폰",
  "Wirehaired Vizsla": "와이어헤어드 비즐라",
  Xoloitzcuintli: "졸로 이츠퀸틀리",
  "Yorkshire Terrier": "요크셔 테리어",
};

export const dogNameK = {
  아펜핀셔: "Affenpinscher",
  "아프간 하운드": "Afghan Hound",
  "아프리카 사냥개": "African Hunting Dog",
  "에어데일 테리어": "Airedale Terrier",
  "아크바시 독": "Akbash Dog",
  아키타: "Akita",
  "알라파 블루 블러드 불독": "Alapaha Blue Blood Bulldog",
  "알래스카 허스키": "Alaskan Husky",
  "알래스카 말라뮤트": "Alaskan Malamute",
  "아메리칸 불독": "American Bulldog",
  "아메리칸 불리": "American Bully",
  "아메리칸 에스키모 독": "American Eskimo Dog",
  "아메리칸 에스키모 독 (미니어처)": "American Eskimo Dog (Miniature)",
  "아메리칸 폭스하운드": "American Foxhound",
  "아메리칸 핏불 테리어": "American Pit Bull Terrier",
  "아메리칸 스태퍼드셔 테리어": "American Staffordshire Terrier",
  "아메리칸 워터 스패니얼": "American Water Spaniel",
  "아나톨리아 목장개": "Anatolian Shepherd Dog",
  "아펜젤러 션넨훈트": "Appenzeller Sennenhund",
  "오스트레일리안 캐틀 독": "Australian Cattle Dog",
  "오스트레일리안 켈피": "Australian Kelpie",
  "오스트레일리안 셰퍼드": "Australian Shepherd",
  "오스트레일리안 테리어": "Australian Terrier",
  아자왁: "Azawakh",
  바르베: "Barbet",
  바센지: "Basenji",
  "바세 블루 드 가스코뉴": "Basset Bleu de Gascogne",
  "바셋 하운드": "Basset Hound",
  비글: "Beagle",
  "비어디드 콜리": "Bearded Collie",
  보시롱: "Beauceron",
  "베들링턴 테리어": "Bedlington Terrier",
  "벨기에 말리노이즈": "Belgian Malinois",
  "벨기에 터뷰런": "Belgian Tervuren",
  "버니즈 마운틴 독": "Bernese Mountain Dog",
  "비숑 프리제": "Bichon Frise",
  "블랙 앤 탄 쿤하운드": "Black and Tan Coonhound",
  블러드하운드: "Bloodhound",
  "블루틱 쿤하운드": "Bluetick Coonhound",
  보어불: "Boerboel",
  "보더 콜리": "Border Collie",
  "보더 테리어": "Border Terrier",
  "보스턴 테리어": "Boston Terrier",
  "부비에 데 플랑드르": "Bouvier des Flandres",
  복서: "Boxer",
  "보이킨 스패니얼": "Boykin Spaniel",
  "이탈리안 포인터": "Bracco Italiano",
  브리아드: "Briard",
  브리트니: "Brittany",
  "불 테리어": "Bull Terrier",
  "불 테리어 (미니어처)": "Bull Terrier (Miniature)",
  불마스티프: "Bullmastiff",
  "케언 테리어": "Cairn Terrier",
  "카네 코르소": "Cane Corso",
  "카디건 웰시 코기": "Cardigan Welsh Corgi",
  "카타훌라 레오파드 독": "Catahoula Leopard Dog",
  "코카시안 셰퍼드 (오브차르카)": "Caucasian Shepherd (Ovcharka)",
  "카발리에 킹 찰스 스패니얼": "Cavalier King Charles Spaniel",
  "체사피크 베이 리트리버": "Chesapeake Bay Retriever",
  "차이니스 크레스티드": "Chinese Crested",
  "차이니스 샤페이": "Chinese Shar-Pei",
  치눅: "Chinook",
  "차우 차우": "Chow Chow",
  "클럼버 스패니얼": "Clumber Spaniel",
  "코커 스패니얼": "Cocker Spaniel",
  "코커 스패니얼 (아메리칸)": "Cocker Spaniel (American)",
  "코튼 드 뚤레아": "Coton de Tulear",
  달마티안: "Dalmatian",
  "도베르만 핀셔": "Doberman Pinscher",
  "도고 아르헨티노": "Dogo Argentino",
  "더치 셰퍼드": "Dutch Shepherd",
  "잉글리쉬 세터": "English Setter",
  "잉글리쉬 셰퍼드": "English Shepherd",
  "잉글리쉬 스프링어 스패니얼": "English Springer Spaniel",
  "잉글리쉬 토이 스패니얼": "English Toy Spaniel",
  "잉글리쉬 토이 테리어": "English Toy Terrier",
  유라시안: "Eurasier",
  "필드 스패니얼": "Field Spaniel",
  "핀란드 랩훈드": "Finnish Lapphund",
  "핀란드 스피츠": "Finnish Spitz",
  "프렌치 불독": "French Bulldog",
  "저먼 핀셔": "German Pinscher",
  "저먼 셰퍼드 독": "German Shepherd Dog",
  "저먼 숏헤어 포인터": "German Shorthaired Pointer",
  "자이언트 슈나우저": "Giant Schnauzer",
  "글렌 오브 이말 테리어": "Glen of Imaal Terrier",
  "골든 리트리버": "Golden Retriever",
  "고든 세터": "Gordon Setter",
  "그레이트 데인": "Great Dane",
  "그레이트 피레니즈": "Great Pyrenees",
  그레이하운드: "Greyhound",
  "브뤼셀 그리폰": "Griffon Bruxellois",
  해리어: "Harrier",
  하바니즈: "Havanese",
  "아이리시 세터": "Irish Setter",
  "아이리시 테리어": "Irish Terrier",
  "아이리시 울프하운드": "Irish Wolfhound",
  "이탈리안 그레이하운드": "Italian Greyhound",
  "재패니스 친": "Japanese Chin",
  "재패니스 스피츠": "Japanese Spitz",
  키스혼드: "Keeshond",
  코몬도르: "Komondor",
  쿠키어혼치: "Kooikerhondje",
  쿠바스: "Kuvasz",
  "라브라도 리트리버": "Labrador Retriever",
  "라고토 로마뇰로": "Lagotto Romagnolo",
  "랭카셔 힐러": "Lancashire Heeler",
  레온베르거: "Leonberger",
  "라사 압소": "Lhasa Apso",
  말티즈: "Maltese",
  "미니어처 아메리칸 셰퍼드": "Miniature American Shepherd",
  "미니어처 핀셔": "Miniature Pinscher",
  "미니어처 슈나우저": "Miniature Schnauzer",
  뉴펀들랜드: "Newfoundland",
  "노퍽 테리어": "Norfolk Terrier",
  "노리치 테리어": "Norwich Terrier",
  "노바 스코샤 덕 톨링 리트리버": "Nova Scotia Duck Tolling Retriever",
  "올드 잉글리쉬 쉽독": "Old English Sheepdog",
  "올드 잉글리쉬 불독": "Olde English Bulldogge",
  파피용: "Papillon",
  페키니즈: "Pekingese",
  "펨브록 웰시 코기": "Pembroke Welsh Corgi",
  "페로 데 프레사 카나리오": "Perro de Presa Canario",
  "파라오 하운드": "Pharaoh Hound",
  플롯트: "Plott",
  포메라니안: "Pomeranian",
  "푸들 (미니어처)": "Poodle (Miniature)",
  "푸들 (토이)": "Poodle (Toy)",
  퍼그: "Pug",
  푸리: "Puli",
  푸미: "Pumi",
  "랫 테리어": "Rat Terrier",
  "레드본 쿤하운드": "Redbone Coonhound",
  "로데시안 루지백": "Rhodesian Ridgeback",
  로트와일러: "Rottweiler",
  "러시안 토이": "Russian Toy",
  "세인트 버나드": "Saint Bernard",
  살루키: "Saluki",
  사모예드: "Samoyed",
  슈퍼크: "Schipperke",
  "스코티시 디어하운드": "Scottish Deerhound",
  "스코티시 테리어": "Scottish Terrier",
  "셰틀랜드 쉽독": "Shetland Sheepdog",
  "시바 이누": "Shiba Inu",
  시쯔: "Shih Tzu",
  "시로 셰퍼드": "Shiloh Shepherd",
  "시베리안 허스키": "Siberian Husky",
  "실키 테리어": "Silky Terrier",
  "스무스 폭스 테리어": "Smooth Fox Terrier",
  "소프트 코티드 휘튼 테리어": "Soft Coated Wheaten Terrier",
  "스페인 워터 독": "Spanish Water Dog",
  "스피노네 이탈리아노": "Spinone Italiano",
  "스태퍼드셔 불 테리어": "Staffordshire Bull Terrier",
  "스탠더드 슈나우저": "Standard Schnauzer",
  "스웨디시 발훈드": "Swedish Vallhund",
  "타이 리지백": "Thai Ridgeback",
  "티베탄 매스티프": "Tibetan Mastiff",
  "티베탄 스패니얼": "Tibetan Spaniel",
  "티베탄 테리어": "Tibetan Terrier",
  "토이 폭스 테리어": "Toy Fox Terrier",
  "트리잉 워커 쿤하운드": "Treeing Walker Coonhound",
  비즐라: "Vizsla",
  와이마라너: "Weimaraner",
  "웰시 스프링어 스패니얼": "Welsh Springer Spaniel",
  "웨스트 하이랜드 화이트 테리어": "West Highland White Terrier",
  위펫: "Whippet",
  "화이트 셰퍼드": "White Shepherd",
  "와이어 폭스 테리어": "Wire Fox Terrier",
  "와이어헤어드 포인팅 그리폰": "Wirehaired Pointing Griffon",
  "와이어헤어드 비즐라": "Wirehaired Vizsla",
  "졸로 이츠퀸틀리": "Xoloitzcuintli",
  "요크셔 테리어": "Yorkshire Terrier",
};
