const idEngname = {
  1: "Affenpinscher",
  2: "Afghan Hound",
  3: "African Hunting Dog",
  4: "Airedale Terrier",
  5: "Akbash Dog",
  6: "Akita",
  7: "Alapaha Blue Blood Bulldog",
  8: "Alaskan Husky",
  9: "Alaskan Malamute",
  10: "American Bulldog",
  11: "American Bully",
  12: "American Eskimo Dog",
  13: "American Eskimo Dog (Miniature)",
  14: "American Foxhound",
  15: "American Pit Bull Terrier",
  16: "American Staffordshire Terrier",
  17: "American Water Spaniel",
  18: "Anatolian Shepherd Dog",
  19: "Appenzeller Sennenhund",
  20: "Aussiedoodle",
  21: "Australian Cattle Dog",
  22: "Australian Kelpie",
  23: "Australian Shepherd",
  24: "Australian Terrier",
  25: "Azawakh",
  26: "Barbet",
  27: "Bassador",
  28: "Basenji",
  29: "Basset Bleu de Gascogne",
  30: "Basset Hound",
  31: "Beagle",
  32: "Bearded Collie",
  33: "Beauceron",
  34: "Bedlington Terrier",
  35: "Belgian Laekenois",
  36: "Belgian Malinois",
  37: "Belgian Sheepdog",
  38: "Belgian Tervuren",
  39: "Bergamasco",
  40: "Berger Picard",
  41: "Bernese Mountain Dog",
  42: "Bichon Frise",
  43: "Black and Tan Coonhound",
  44: "Black Russian Terrie",
  45: "Bloodhound",
  46: "Blue Picardy Spaniel",
  47: "Bluetick Coonhound",
  48: "Boerboel",
  49: "Bolognese",
  50: "Border Collie",
  51: "Border Terrier",
  52: "Borzoi",
  53: "Boston Terrier",
  54: "Bouvier des Flandres",
  55: "Boxer",
  56: "Boykin Spaniel",
  57: "Bracco Italiano",
  58: "Briard",
  59: "Brittany",
  60: "Brussels Griffon",
  61: "Bull Terrier",
  62: "Bull Terrier (Miniature)",
  63: "Bulldog",
  64: "Bullmastiff",
  65: "Cairn Terrier",
  66: "Canaan Dog",
  67: "Cane Corso",
  68: "Cardigan Welsh Corgi",
  69: "Catahoula Leopard Dog",
  70: "Caucasian Shepherd (Ovcharka)",
  71: "Cavalier King Charles Spaniel",
  72: "Cavapom",
  73: "Cavapoo",
  74: "Cesky Terrier",
  75: "Chart Polski",
  76: "Chesapeake Bay Retriever",
  77: "Companionship",
  78: "Chinese Crested",
  79: "Chinese Shar-Pei",
  80: "Chinook",
  81: "Chow Chow",
  82: "Chug",
  83: "Cirneco dell",
  84: "Clumber Spaniel",
  85: "Cockapoo",
  86: "Cocker Spaniel",
  87: "Cocker Spaniel (American)",
  88: "Collie",
  89: "Coton de Tulear",
  90: "Curly-Coated Retriever",
  91: "Dachshund",
  92: "Dalmatian",
  93: "Dandie Dinmont Terrier",
  94: "Doberman Pinscher",
  95: "Dogo Argentino",
  96: "Dogue de Bordeaux",
  97: "Doxiepoo",
  98: "Dutch Shepherd",
  99: "Dutch Shepherd",
  100: "English Foxhound",
  101: "English Setter",
  102: "English Shepherd",
  103: "English Springer Spaniel",
  104: "English Toy Spaniel",
  105: "English Toy Terrier",
  106: "Entlebucher Mountain Dog",
  107: "Eurasier",
  108: "Field Spaniel",
  109: "Fila Brasileiro",
  110: "Finnish Lapphund",
  111: "Finnish Spitz",
  112: "Flat-Coated Retriever",
  113: "French Bulldog",
  114: "German Pinscher",
  115: "German Shepherd Dog",
  116: "German Shorthaired Pointer",
  117: "German Spitz",
  118: "German Wirehaired Pointer",
  119: "Giant Schnauzer",
  120: "Glen of Imaal Terrier",
  121: "Golden Retriever",
  122: "Goldendoodle",
  123: "Gordon Setter",
  124: "Great Dane",
  125: "Great Pyrenees",
  126: "Greater Swiss Mountain Dog",
  127: "Greyhound",
  128: "Griffon Bruxellois",
  129: "Harrier",
  130: "Havanese",
  131: "Ibizan Hound",
  132: "Icelandic Sheepdog",
  133: "Irish Red and White Setter",
  134: "Irish Setter",
  135: "Irish Terrier",
  136: "Irish Water Spaniel",
  137: "Irish Wolfhound",
  138: "Italian Greyhound",
  139: "Jack Russell Terrier",
  140: "Japanese Chin",
  141: "Japanese Spitz",
  142: "Keeshond",
  143: "Kerry Blue Terrier",
  144: "Komondor",
  145: "Kooikerhondje",
  146: "Kromfohrlander",
  147: "Kuvasz",
  148: "Labradoodle",
  149: "Labrador Retriever",
  150: "Lacy Dog",
  151: "Lagotto Romagnolo",
  152: "Lakeland Terrier",
  153: "Lancashire Heeler",
  154: "Large Munsterlander",
  155: "Leonberger",
  156: "Lhasa Apso",
  157: "Lhasapoo",
  158: "Longdog",
  159: "Lowchen",
  160: "Lurcher",
  161: "Maltese",
  162: "Maltipoo",
  163: "Manchester Terrier",
  164: "Mastiff",
  165: "Miniature American Shepherd",
  166: "Miniature Bull Terrier",
  167: "Miniature Pinscher",
  168: "Miniature Schnauzer",
  169: "Mudi",
  170: "Neapolitan Mastiff",
  171: "Newfoundland",
  172: "Norfolk Terrier",
  173: "Norwegian Buhund",
  174: "Norwegian Elkhound",
  175: "Norwegian Lundehund",
  176: "Norwich Terrier",
  177: "Nova Scotia Duck Tolling Retriever",
  178: "Old English Sheepdog",
  179: "Olde English Bulldogge",
  180: "Otterhound",
  181: "Papillon",
  182: "Pekeapoo",
  183: "Pekingese",
  184: "Pembroke Welsh Corgi",
  185: "Perro de Presa Canario",
  186: "Peruvian Inca Orchid",
  187: "Petit Basset Griffon Vendeen",
  188: "Pharaoh Hound",
  189: "Plott",
  190: "Pointer",
  191: "Polish Lowland Sheepdog",
  192: "Pomapoo",
  193: "Pomeranian",
  194: "Pomsky",
  195: "Poodle",
  196: "Poodle (Miniature)",
  197: "Poodle (Toy)",
  198: "Portuguese Podengo",
  199: "Portuguese Water Dog",
  200: "Presa Canario",
  201: "Pug",
  202: "Pugapoo",
  203: "Puggle",
  204: "Puli",
  205: "Pumi",
  206: "Pyrenean Shepherd",
  207: "Rat Terrier",
  208: "Redbone Coonhound",
  209: "Rhodesian Ridgeback",
  210: "Rottweiler",
  211: "Russian Toy",
  212: "Saint Bernard",
  213: "Saluki",
  214: "Samoyed",
  215: "Schapendoes",
  216: "Schipperke",
  217: "Schnoodle",
  218: "Scottish Deerhound",
  219: "Scottish Terrier",
  220: "Sealyham Terrier",
  221: "Shetland Sheepdog",
  222: "Shiba Inu",
  223: "Shih Tzu",
  224: "Shihpoo",
  225: "Shiloh Shepherd",
  226: "Siberian Husky",
  227: "Silken Windhound",
  228: "Silky Terrier",
  229: "Skye Terrier",
  230: "Sloughi",
  231: "Small Munsterlander Pointer",
  232: "Smooth Fox Terrier",
  233: "Soft Coated Wheaten Terrier",
  234: "Spanish Greyhound",
  235: "Spanish Water Dog",
  236: "Spinone Italiano",
  237: "Sprollie",
  238: "Staffordshire Bull Terrier",
  239: "Standard Schnauzer",
  240: "Staffordshire Bull Terrier",
  241: "Swedish Lapphund",
  242: "Swedish Vallhund",
  243: "Thai Ridgeback",
  244: "Tibetan Mastiff",
  245: "Tibetan Spaniel",
  246: "Tibetan Terrier",
  247: "Tosa Ken",
  248: "Toy Fox Terrier",
  249: "Toy Poodle",
  250: "Treeing Walker Coonhound",
  251: "Vizsla",
  252: "Volpino Italiano",
  253: "Weimaraner",
  254: "Welsh Springer Spaniel",
  255: "Welsh Terrier",
  256: "West Highland White Terrier",
  257: "Whippet",
  258: "White Shepherd",
  259: "Wire Fox Terrier",
  260: "Wirehaired Pointing Griffon",
  261: "Wirehaired Vizsla",
  262: "Xoloitzcuintli",
  263: "Yorkipoo",
  264: "Yorkshire Terrier",
};

const idKorname = {
  1: "아펜핀셔",
  2: "아프간 하운드",
  3: "아프리카 혼티드독",
  4: "에어데일 테리어",
  5: "아크바시 독",
  6: "아키타",
  7: "알라파하 블루 블러드 불독",
  8: "알래스칸 허스키",
  9: "알래스칸 말라뮤트",
  10: "아메리칸 불독",
  11: "아메리칸 불리",
  12: "아메리칸 에스키모 독",
  13: "미니어처 아메리칸 에스키모 독",
  14: "아메리칸 폭스하운드",
  15: "아메리칸 핏불 테리어",
  16: "아메리칸 스태퍼드셔 테리어",
  17: "아메리칸 워터 스패니얼",
  18: "아나톨리안 세퍼드 독",
  19: "아펜젤러 세넨훈트",
  20: "오시도들",
  21: "오스트레일리안 캐틀 독",
  22: "오스트레일리언 켈피",
  23: "오스트레일리언 셰퍼드",
  24: "오스트레일리언 테리어",
  25: "아자와크",
  26: "바베",
  27: "바소더",
  28: "바센지",
  29: "바세 블루 드 가스코뉴",
  30: "바세 하운드",
  31: "비글",
  32: "비어디드 콜리",
  33: "보시롱",
  34: "베들링턴 테리어",
  35: "벨기에 라이켄와",
  36: "벨기에 말리노이즈",
  37: "벨기에 쉽독",
  38: "벨기에 터뷰렌",
  39: "베르가마스코",
  40: "베르저 피카르",
  41: "버니즈 마운틴 독",
  42: "비숑 프리제",
  43: "블랙 앤 탄 쿤하운드",
  44: "블랙 러시안 테리어",
  45: "블러드하운드",
  46: "블루 피카르디 스패니얼",
  47: "블루틱 쿤하운드",
  48: "보어불",
  49: "볼로냐즈",
  50: "보더 콜리",
  51: "보더 테리어",
  52: "보르조이",
  53: "보스턴 테리어",
  54: "부비에 데 플랑드르",
  55: "복서",
  56: "보이킨 스패니얼",
  57: "브라코 이탈리아노",
  58: "브리아드",
  59: "브리트니",
  60: "브뤼셀 그리펀",
  61: "불 테리어",
  62: "미니어처 불 테리어",
  63: "불독",
  64: "불마스티프",
  65: "케언 테리어",
  66: "카나안 독",
  67: "카네코르소",
  68: "카디건 웰시 코기",
  69: "카타훌라 리오파드 독",
  70: "코카시안 셰퍼드 (오브차르카)",
  71: "캐벌리어 킹 찰스 스패니얼",
  72: "캐파폼",
  73: "캐프푸",
  74: "체스키 테리어",
  75: "차트 폴스키",
  76: "체사피크 베이 리트리버",
  77: "동반자",
  78: "중국 크레스티드",
  79: "중국 샤페이",
  80: "추크",
  81: "차우 차우",
  82: "차그",
  83: "치르네코 델 에트나",
  84: "클럼버 스패니얼",
  85: "코커푸",
  86: "코커 스패니얼",
  87: "코커 스패니얼 (아메리칸)",
  88: "콜리",
  89: "코튼 드 툴레아",
  90: "컬리 코티드 리트리버",
  91: "닥스훈드",
  92: "달마티안",
  93: "덴디 딘몬트 테리어",
  94: "도베르만 핀셔",
  95: "도고 아르헨티노",
  96: "도그 드 보르도",
  97: "닥스푸",
  98: "더치 쉽허드",
  99: "더치 쉽허드",
  100: "잉글리쉬 폭스하운드",
  101: "잉글리쉬 세터",
  102: "잉글리쉬 쉽허드",
  103: "잉글리쉬 스프링어 스패니얼",
  104: "잉글리쉬 토이 스패니얼",
  105: "잉글리쉬 토이 테리어",
  106: "엔틀부허 마운틴 독",
  107: "유라시어",
  108: "필드 스패니얼",
  109: "피라 브라질레이로",
  110: "핀란드 랩훈드",
  111: "핀란드 스피츠",
  112: "플랫코티드 리트리버",
  113: "프렌치 불도그",
  114: "저먼 핀셔",
  115: "저먼 셰퍼드 독",
  116: "저먼 숏헤어드 포인터",
  117: "저먼 스피츠",
  118: "저먼 와이어헤어드 포인터",
  119: "자이언트 스나우저",
  120: "글렌 오브 이맬 테리어",
  121: "골든 리트리버",
  122: "골덴두들",
  123: "고든 세터",
  124: "그레이트 데인",
  125: "그레이트 피레니즈",
  126: "그레이터 스위스 마운틴 독",
  127: "그레이하운드",
  128: "그리폰 브뤼셀로와",
  129: "해리어",
  130: "하바니즈",
  131: "이비잔 하운드",
  132: "아이슬란드 쉽독",
  133: "아이리시 레드 앤 화이트 세터",
  134: "아이리시 세터",
  135: "아이리시 테리어",
  136: "아이리시 워터 스패니얼",
  137: "아이리시 울프하운드",
  138: "이탈리안 그레이하운드",
  139: "잭 러셀 테리어",
  140: "일본 친",
  141: "일본 스피츠",
  142: "키스혼드",
  143: "케리 블루 테리어",
  144: "코몬도르",
  145: "쿠이커혼드",
  146: "크롬포허랜더",
  147: "쿠바스",
  148: "라브라도들",
  149: "라브라도 리트리버",
  150: "레이시 독",
  151: "라고토 로마뇰로",
  152: "레이클랜드 테리어",
  153: "란카셔 힐러",
  154: "라지 먼스터랜더",
  155: "레온베르거",
  156: "라사 압소",
  157: "라사푸",
  158: "롱독",
  159: "로첸",
  160: "러처",
  161: "말티즈",
  162: "말티푸",
  163: "맨체스터 테리어",
  164: "마스티프",
  165: "미니어처 아메리칸 셰퍼드",
  166: "미니어처 불 테리어",
  167: "미니어처 핀셔",
  168: "미니어처 슈나우저",
  169: "무디",
  170: "나폴리탄 마스티프",
  171: "뉴펀들랜드",
  172: "노퍽 테리어",
  173: "노르웨이 부훈드",
  174: "노르웨이 엘크하운드",
  175: "노르웨이 룬데훈드",
  176: "노리치 테리어",
  177: "노바 스코샤 덕 톨링 리트리버",
  178: "올드 잉글리쉬 숩독",
  179: "올드 잉글리쉬 불독",
  180: "오터하운드",
  181: "파피용",
  182: "페키푸",
  183: "페키니즈",
  184: "펨브로크 웰시 코기",
  185: "페로 데 프레사 카나리오",
  186: "페루비안 인카 오키드",
  187: "쁘띠프포 베송 그리펀 반드른",
  188: "파라오 하운드",
  189: "플롯",
  190: "포인터",
  191: "폴리시 로우랜드 쉽독",
  192: "포마푸",
  193: "포메라니안",
  194: "폼스키",
  195: "푸들",
  196: "미니어처 푸들",
  197: "토이 푸들",
  198: "포르투갈리아 포뎅고",
  199: "포르투갈 워터 독",
  200: "프레사 카나리오",
  201: "퍼그",
  202: "퍼가푸",
  203: "퍼글",
  204: "풀리",
  205: "푸미",
  206: "피레네안 셰퍼드",
  207: "랫 테리어",
  208: "레드본 쿤하운드",
  209: "로데시안 릿지백",
  210: "로트와일러",
  211: "러시안 토이",
  212: "세인트 버나드",
  213: "살루키",
  214: "사모예드",
  215: "샤펜도스",
  216: "스키퍼키",
  217: "슈누들",
  218: "스코티시 디어하운드",
  219: "스코티시 테리어",
  220: "실리햄 테리어",
  221: "셰틀랜드 쉽독",
  222: "시바 이누",
  223: "시츄",
  224: "시푸",
  225: "실로 세퍼드",
  226: "시베리안 허스키",
  227: "실큰 윈드하운드",
  228: "실키 테리어",
  229: "스카이 테리어",
  230: "슬로우기",
  231: "스몰 문스터랜더 포인터",
  232: "스무스 폭스 테리어",
  233: "소프트 코티드 휘튼 테리어",
  234: "스페니쉬 그레이하운드",
  235: "스페니쉬 워터 독",
  236: "스피노네 이탈리아노",
  237: "스프롤리",
  238: "스태퍼드셔 불 테리어",
  239: "스탠다드 슈나우저",
  240: "스태퍼드셔 불 테리어",
  241: "스웨디시 랩훈드",
  242: "스웨디시 발훈드",
  243: "타이 리지백",
  244: "티베탄 매스티프",
  245: "티베탄 스파니얼",
  246: "티베탄 테리어",
  247: "토사 켄",
  248: "토이 폭스 테리어",
  249: "토이 푸들",
  250: "트리잉 워커 쿤하운드",
  251: "비즐라",
  252: "볼피노 이탈리아노",
  253: "와이마라너",
  254: "웰시 스프링거 스패니얼",
  255: "웰시 테리어",
  256: "웨스트 하이랜드 화이트 테리어",
  257: "휘펫",
  258: "화이트 세퍼드",
  259: "와이어 폭스 테리어",
  260: "와이어헤어 포인팅 그리펀",
  261: "와이어헤어 비즐라",
  262: "쇼로이츠쿠인틀리",
  263: "요크푸",
  264: "요크셔 테리어",
};

const engnameId = {
  Affenpinscher: 1,
  "Afghan Hound": 2,
  "African Hunting Dog": 3,
  "Airedale Terrier": 4,
  "Akbash Dog": 5,
  Akita: 6,
  "Alapaha Blue Blood Bulldog": 7,
  "Alaskan Husky": 8,
  "Alaskan Malamute": 9,
  "American Bulldog": 10,
  "American Bully": 11,
  "American Eskimo Dog": 12,
  "American Eskimo Dog (Miniature)": 13,
  "American Foxhound": 14,
  "American Pit Bull Terrier": 15,
  "American Staffordshire Terrier": 16,
  "American Water Spaniel": 17,
  "Anatolian Shepherd Dog": 18,
  "Appenzeller Sennenhund": 19,
  Aussiedoodle: 20,
  "Australian Cattle Dog": 21,
  "Australian Kelpie": 22,
  "Australian Shepherd": 23,
  "Australian Terrier": 24,
  Azawakh: 25,
  Barbet: 26,
  Bassador: 27,
  Basenji: 28,
  "Basset Bleu de Gascogne": 29,
  "Basset Hound": 30,
  Beagle: 31,
  "Bearded Collie": 32,
  Beauceron: 33,
  "Bedlington Terrier": 34,
  "Belgian Laekenois": 35,
  "Belgian Malinois": 36,
  "Belgian Sheepdog": 37,
  "Belgian Tervuren": 38,
  Bergamasco: 39,
  "Berger Picard": 40,
  "Bernese Mountain Dog": 41,
  "Bichon Frise": 42,
  "Black and Tan Coonhound": 43,
  "Black Russian Terrie": 44,
  Bloodhound: 45,
  "Blue Picardy Spaniel": 46,
  "Bluetick Coonhound": 47,
  Boerboel: 48,
  Bolognese: 49,
  "Border Collie": 50,
  "Border Terrier": 51,
  Borzoi: 52,
  "Boston Terrier": 53,
  "Bouvier des Flandres": 54,
  Boxer: 55,
  "Boykin Spaniel": 56,
  "Bracco Italiano": 57,
  Briard: 58,
  Brittany: 59,
  "Brussels Griffon": 60,
  "Bull Terrier": 61,
  "Bull Terrier (Miniature)": 62,
  Bulldog: 63,
  Bullmastiff: 64,
  "Cairn Terrier": 65,
  "Canaan Dog": 66,
  "Cane Corso": 67,
  "Cardigan Welsh Corgi": 68,
  "Catahoula Leopard Dog": 69,
  "Caucasian Shepherd (Ovcharka)": 70,
  "Cavalier King Charles Spaniel": 71,
  Cavapom: 72,
  Cavapoo: 73,
  "Cesky Terrier": 74,
  "Chart Polski": 75,
  "Chesapeake Bay Retriever": 76,
  Companionship: 77,
  "Chinese Crested": 78,
  "Chinese Shar-Pei": 79,
  Chinook: 80,
  "Chow Chow": 81,
  Chug: 82,
  "Cirneco dell": 83,
  "Clumber Spaniel": 84,
  Cockapoo: 85,
  "Cocker Spaniel": 86,
  "Cocker Spaniel (American)": 87,
  Collie: 88,
  "Coton de Tulear": 89,
  "Curly-Coated Retriever": 90,
  Dachshund: 91,
  Dalmatian: 92,
  "Dandie Dinmont Terrier": 93,
  "Doberman Pinscher": 94,
  "Dogo Argentino": 95,
  "Dogue de Bordeaux": 96,
  Doxiepoo: 97,
  "Dutch Shepherd": 99,
  "English Foxhound": 100,
  "English Setter": 101,
  "English Shepherd": 102,
  "English Springer Spaniel": 103,
  "English Toy Spaniel": 104,
  "English Toy Terrier": 105,
  "Entlebucher Mountain Dog": 106,
  Eurasier: 107,
  "Field Spaniel": 108,
  "Fila Brasileiro": 109,
  "Finnish Lapphund": 110,
  "Finnish Spitz": 111,
  "Flat-Coated Retriever": 112,
  "French Bulldog": 113,
  "German Pinscher": 114,
  "German Shepherd Dog": 115,
  "German Shorthaired Pointer": 116,
  "German Spitz": 117,
  "German Wirehaired Pointer": 118,
  "Giant Schnauzer": 119,
  "Glen of Imaal Terrier": 120,
  "Golden Retriever": 121,
  Goldendoodle: 122,
  "Gordon Setter": 123,
  "Great Dane": 124,
  "Great Pyrenees": 125,
  "Greater Swiss Mountain Dog": 126,
  Greyhound: 127,
  "Griffon Bruxellois": 128,
  Harrier: 129,
  Havanese: 130,
  "Ibizan Hound": 131,
  "Icelandic Sheepdog": 132,
  "Irish Red and White Setter": 133,
  "Irish Setter": 134,
  "Irish Terrier": 135,
  "Irish Water Spaniel": 136,
  "Irish Wolfhound": 137,
  "Italian Greyhound": 138,
  "Jack Russell Terrier": 139,
  "Japanese Chin": 140,
  "Japanese Spitz": 141,
  Keeshond: 142,
  "Kerry Blue Terrier": 143,
  Komondor: 144,
  Kooikerhondje: 145,
  Kromfohrlander: 146,
  Kuvasz: 147,
  Labradoodle: 148,
  "Labrador Retriever": 149,
  "Lacy Dog": 150,
  "Lagotto Romagnolo": 151,
  "Lakeland Terrier": 152,
  "Lancashire Heeler": 153,
  "Large Munsterlander": 154,
  Leonberger: 155,
  "Lhasa Apso": 156,
  Lhasapoo: 157,
  Longdog: 158,
  Lowchen: 159,
  Lurcher: 160,
  Maltese: 161,
  Maltipoo: 162,
  "Manchester Terrier": 163,
  Mastiff: 164,
  "Miniature American Shepherd": 165,
  "Miniature Bull Terrier": 166,
  "Miniature Pinscher": 167,
  "Miniature Schnauzer": 168,
  Mudi: 169,
  "Neapolitan Mastiff": 170,
  Newfoundland: 171,
  "Norfolk Terrier": 172,
  "Norwegian Buhund": 173,
  "Norwegian Elkhound": 174,
  "Norwegian Lundehund": 175,
  "Norwich Terrier": 176,
  "Nova Scotia Duck Tolling Retriever": 177,
  "Old English Sheepdog": 178,
  "Olde English Bulldogge": 179,
  Otterhound: 180,
  Papillon: 181,
  Pekeapoo: 182,
  Pekingese: 183,
  "Pembroke Welsh Corgi": 184,
  "Perro de Presa Canario": 185,
  "Peruvian Inca Orchid": 186,
  "Petit Basset Griffon Vendeen": 187,
  "Pharaoh Hound": 188,
  Plott: 189,
  Pointer: 190,
  "Polish Lowland Sheepdog": 191,
  Pomapoo: 192,
  Pomeranian: 193,
  Pomsky: 194,
  Poodle: 195,
  "Poodle (Miniature)": 196,
  "Poodle (Toy)": 197,
  "Portuguese Podengo": 198,
  "Portuguese Water Dog": 199,
  "Presa Canario": 200,
  Pug: 201,
  Pugapoo: 202,
  Puggle: 203,
  Puli: 204,
  Pumi: 205,
  "Pyrenean Shepherd": 206,
  "Rat Terrier": 207,
  "Redbone Coonhound": 208,
  "Rhodesian Ridgeback": 209,
  Rottweiler: 210,
  "Russian Toy": 211,
  "Saint Bernard": 212,
  Saluki: 213,
  Samoyed: 214,
  Schapendoes: 215,
  Schipperke: 216,
  Schnoodle: 217,
  "Scottish Deerhound": 218,
  "Scottish Terrier": 219,
  "Sealyham Terrier": 220,
  "Shetland Sheepdog": 221,
  "Shiba Inu": 222,
  "Shih Tzu": 223,
  Shihpoo: 224,
  "Shiloh Shepherd": 225,
  "Siberian Husky": 226,
  "Silken Windhound": 227,
  "Silky Terrier": 228,
  "Skye Terrier": 229,
  Sloughi: 230,
  "Small Munsterlander Pointer": 231,
  "Smooth Fox Terrier": 232,
  "Soft Coated Wheaten Terrier": 233,
  "Spanish Greyhound": 234,
  "Spanish Water Dog": 235,
  "Spinone Italiano": 236,
  Sprollie: 237,
  "Staffordshire Bull Terrier": 240,
  "Standard Schnauzer": 239,
  "Swedish Lapphund": 241,
  "Swedish Vallhund": 242,
  "Thai Ridgeback": 243,
  "Tibetan Mastiff": 244,
  "Tibetan Spaniel": 245,
  "Tibetan Terrier": 246,
  "Tosa Ken": 247,
  "Toy Fox Terrier": 248,
  "Toy Poodle": 249,
  "Treeing Walker Coonhound": 250,
  Vizsla: 251,
  "Volpino Italiano": 252,
  Weimaraner: 253,
  "Welsh Springer Spaniel": 254,
  "Welsh Terrier": 255,
  "West Highland White Terrier": 256,
  Whippet: 257,
  "White Shepherd": 258,
  "Wire Fox Terrier": 259,
  "Wirehaired Pointing Griffon": 260,
  "Wirehaired Vizsla": 261,
  Xoloitzcuintli: 262,
  Yorkipoo: 263,
  "Yorkshire Terrier": 264,
};

const kornameId = {
  아펜핀셔: 1,
  "아프간 하운드": 2,
  "아프리카 혼티드독": 3,
  "에어데일 테리어": 4,
  "아크바시 독": 5,
  아키타: 6,
  "알라파하 블루 블러드 불독": 7,
  "알래스칸 허스키": 8,
  "알래스칸 말라뮤트": 9,
  "아메리칸 불독": 10,
  "아메리칸 불리": 11,
  "아메리칸 에스키모 독": 12,
  "미니어처 아메리칸 에스키모 독": 13,
  "아메리칸 폭스하운드": 14,
  "아메리칸 핏불 테리어": 15,
  "아메리칸 스태퍼드셔 테리어": 16,
  "아메리칸 워터 스패니얼": 17,
  "아나톨리안 세퍼드 독": 18,
  "아펜젤러 세넨훈트": 19,
  오시도들: 20,
  "오스트레일리안 캐틀 독": 21,
  "오스트레일리언 켈피": 22,
  "오스트레일리언 셰퍼드": 23,
  "오스트레일리언 테리어": 24,
  아자와크: 25,
  바베: 26,
  바소더: 27,
  바센지: 28,
  "바세 블루 드 가스코뉴": 29,
  "바세 하운드": 30,
  비글: 31,
  "비어디드 콜리": 32,
  보시롱: 33,
  "베들링턴 테리어": 34,
  "벨기에 라이켄와": 35,
  "벨기에 말리노이즈": 36,
  "벨기에 쉽독": 37,
  "벨기에 터뷰렌": 38,
  베르가마스코: 39,
  "베르저 피카르": 40,
  "버니즈 마운틴 독": 41,
  "비숑 프리제": 42,
  "블랙 앤 탄 쿤하운드": 43,
  "블랙 러시안 테리어": 44,
  블러드하운드: 45,
  "블루 피카르디 스패니얼": 46,
  "블루틱 쿤하운드": 47,
  보어불: 48,
  볼로냐즈: 49,
  "보더 콜리": 50,
  "보더 테리어": 51,
  보르조이: 52,
  "보스턴 테리어": 53,
  "부비에 데 플랑드르": 54,
  복서: 55,
  "보이킨 스패니얼": 56,
  "브라코 이탈리아노": 57,
  브리아드: 58,
  브리트니: 59,
  "브뤼셀 그리펀": 60,
  "불 테리어": 61,
  "미니어처 불 테리어": 166,
  불독: 63,
  불마스티프: 64,
  "케언 테리어": 65,
  "카나안 독": 66,
  카네코르소: 67,
  "카디건 웰시 코기": 68,
  "카타훌라 리오파드 독": 69,
  "코카시안 셰퍼드 (오브차르카)": 70,
  "캐벌리어 킹 찰스 스패니얼": 71,
  캐파폼: 72,
  캐프푸: 73,
  "체스키 테리어": 74,
  "차트 폴스키": 75,
  "체사피크 베이 리트리버": 76,
  동반자: 77,
  "중국 크레스티드": 78,
  "중국 샤페이": 79,
  추크: 80,
  "차우 차우": 81,
  차그: 82,
  "치르네코 델 에트나": 83,
  "클럼버 스패니얼": 84,
  코커푸: 85,
  "코커 스패니얼": 86,
  "코커 스패니얼 (아메리칸)": 87,
  콜리: 88,
  "코튼 드 툴레아": 89,
  "컬리 코티드 리트리버": 90,
  닥스훈드: 91,
  달마티안: 92,
  "덴디 딘몬트 테리어": 93,
  "도베르만 핀셔": 94,
  "도고 아르헨티노": 95,
  "도그 드 보르도": 96,
  닥스푸: 97,
  "더치 쉽허드": 99,
  "잉글리쉬 폭스하운드": 100,
  "잉글리쉬 세터": 101,
  "잉글리쉬 쉽허드": 102,
  "잉글리쉬 스프링어 스패니얼": 103,
  "잉글리쉬 토이 스패니얼": 104,
  "잉글리쉬 토이 테리어": 105,
  "엔틀부허 마운틴 독": 106,
  유라시어: 107,
  "필드 스패니얼": 108,
  "피라 브라질레이로": 109,
  "핀란드 랩훈드": 110,
  "핀란드 스피츠": 111,
  "플랫코티드 리트리버": 112,
  "프렌치 불도그": 113,
  "저먼 핀셔": 114,
  "저먼 셰퍼드 독": 115,
  "저먼 숏헤어드 포인터": 116,
  "저먼 스피츠": 117,
  "저먼 와이어헤어드 포인터": 118,
  "자이언트 스나우저": 119,
  "글렌 오브 이맬 테리어": 120,
  "골든 리트리버": 121,
  골덴두들: 122,
  "고든 세터": 123,
  "그레이트 데인": 124,
  "그레이트 피레니즈": 125,
  "그레이터 스위스 마운틴 독": 126,
  그레이하운드: 127,
  "그리폰 브뤼셀로와": 128,
  해리어: 129,
  하바니즈: 130,
  "이비잔 하운드": 131,
  "아이슬란드 쉽독": 132,
  "아이리시 레드 앤 화이트 세터": 133,
  "아이리시 세터": 134,
  "아이리시 테리어": 135,
  "아이리시 워터 스패니얼": 136,
  "아이리시 울프하운드": 137,
  "이탈리안 그레이하운드": 138,
  "잭 러셀 테리어": 139,
  "일본 친": 140,
  "일본 스피츠": 141,
  키스혼드: 142,
  "케리 블루 테리어": 143,
  코몬도르: 144,
  쿠이커혼드: 145,
  크롬포허랜더: 146,
  쿠바스: 147,
  라브라도들: 148,
  "라브라도 리트리버": 149,
  "레이시 독": 150,
  "라고토 로마뇰로": 151,
  "레이클랜드 테리어": 152,
  "란카셔 힐러": 153,
  "라지 먼스터랜더": 154,
  레온베르거: 155,
  "라사 압소": 156,
  라사푸: 157,
  롱독: 158,
  로첸: 159,
  러처: 160,
  말티즈: 161,
  말티푸: 162,
  "맨체스터 테리어": 163,
  마스티프: 164,
  "미니어처 아메리칸 셰퍼드": 165,
  "미니어처 핀셔": 167,
  "미니어처 슈나우저": 168,
  무디: 169,
  "나폴리탄 마스티프": 170,
  뉴펀들랜드: 171,
  "노퍽 테리어": 172,
  "노르웨이 부훈드": 173,
  "노르웨이 엘크하운드": 174,
  "노르웨이 룬데훈드": 175,
  "노리치 테리어": 176,
  "노바 스코샤 덕 톨링 리트리버": 177,
  "올드 잉글리쉬 숩독": 178,
  "올드 잉글리쉬 불독": 179,
  오터하운드: 180,
  파피용: 181,
  페키푸: 182,
  페키니즈: 183,
  "펨브로크 웰시 코기": 184,
  "페로 데 프레사 카나리오": 185,
  "페루비안 인카 오키드": 186,
  "쁘띠프포 베송 그리펀 반드른": 187,
  "파라오 하운드": 188,
  플롯: 189,
  포인터: 190,
  "폴리시 로우랜드 쉽독": 191,
  포마푸: 192,
  포메라니안: 193,
  폼스키: 194,
  푸들: 195,
  "미니어처 푸들": 196,
  "토이 푸들": 249,
  "포르투갈리아 포뎅고": 198,
  "포르투갈 워터 독": 199,
  "프레사 카나리오": 200,
  퍼그: 201,
  퍼가푸: 202,
  퍼글: 203,
  풀리: 204,
  푸미: 205,
  "피레네안 셰퍼드": 206,
  "랫 테리어": 207,
  "레드본 쿤하운드": 208,
  "로데시안 릿지백": 209,
  로트와일러: 210,
  "러시안 토이": 211,
  "세인트 버나드": 212,
  살루키: 213,
  사모예드: 214,
  샤펜도스: 215,
  스키퍼키: 216,
  슈누들: 217,
  "스코티시 디어하운드": 218,
  "스코티시 테리어": 219,
  "실리햄 테리어": 220,
  "셰틀랜드 쉽독": 221,
  "시바 이누": 222,
  시츄: 223,
  시푸: 224,
  "실로 세퍼드": 225,
  "시베리안 허스키": 226,
  "실큰 윈드하운드": 227,
  "실키 테리어": 228,
  "스카이 테리어": 229,
  슬로우기: 230,
  "스몰 문스터랜더 포인터": 231,
  "스무스 폭스 테리어": 232,
  "소프트 코티드 휘튼 테리어": 233,
  "스페니쉬 그레이하운드": 234,
  "스페니쉬 워터 독": 235,
  "스피노네 이탈리아노": 236,
  스프롤리: 237,
  "스태퍼드셔 불 테리어": 240,
  "스탠다드 슈나우저": 239,
  "스웨디시 랩훈드": 241,
  "스웨디시 발훈드": 242,
  "타이 리지백": 243,
  "티베탄 매스티프": 244,
  "티베탄 스파니얼": 245,
  "티베탄 테리어": 246,
  "토사 켄": 247,
  "토이 폭스 테리어": 248,
  "트리잉 워커 쿤하운드": 250,
  비즐라: 251,
  "볼피노 이탈리아노": 252,
  와이마라너: 253,
  "웰시 스프링거 스패니얼": 254,
  "웰시 테리어": 255,
  "웨스트 하이랜드 화이트 테리어": 256,
  휘펫: 257,
  "화이트 세퍼드": 258,
  "와이어 폭스 테리어": 259,
  "와이어헤어 포인팅 그리펀": 260,
  "와이어헤어 비즐라": 261,
  쇼로이츠쿠인틀리: 262,
  요크푸: 263,
  "요크셔 테리어": 264,
};

const engnameKorname = {
  Affenpinscher: "아펜핀셔",
  "Afghan Hound": "아프간 하운드",
  "African Hunting Dog": "아프리카 혼티드독",
  "Airedale Terrier": "에어데일 테리어",
  "Akbash Dog": "아크바시 독",
  Akita: "아키타",
  "Alapaha Blue Blood Bulldog": "알라파하 블루 블러드 불독",
  "Alaskan Husky": "알래스칸 허스키",
  "Alaskan Malamute": "알래스칸 말라뮤트",
  "American Bulldog": "아메리칸 불독",
  "American Bully": "아메리칸 불리",
  "American Eskimo Dog": "아메리칸 에스키모 독",
  "American Eskimo Dog (Miniature)": "미니어처 아메리칸 에스키모 독",
  "American Foxhound": "아메리칸 폭스하운드",
  "American Pit Bull Terrier": "아메리칸 핏불 테리어",
  "American Staffordshire Terrier": "아메리칸 스태퍼드셔 테리어",
  "American Water Spaniel": "아메리칸 워터 스패니얼",
  "Anatolian Shepherd Dog": "아나톨리안 세퍼드 독",
  "Appenzeller Sennenhund": "아펜젤러 세넨훈트",
  Aussiedoodle: "오시도들",
  "Australian Cattle Dog": "오스트레일리안 캐틀 독",
  "Australian Kelpie": "오스트레일리언 켈피",
  "Australian Shepherd": "오스트레일리언 셰퍼드",
  "Australian Terrier": "오스트레일리언 테리어",
  Azawakh: "아자와크",
  Barbet: "바베",
  Bassador: "바소더",
  Basenji: "바센지",
  "Basset Bleu de Gascogne": "바세 블루 드 가스코뉴",
  "Basset Hound": "바세 하운드",
  Beagle: "비글",
  "Bearded Collie": "비어디드 콜리",
  Beauceron: "보시롱",
  "Bedlington Terrier": "베들링턴 테리어",
  "Belgian Laekenois": "벨기에 라이켄와",
  "Belgian Malinois": "벨기에 말리노이즈",
  "Belgian Sheepdog": "벨기에 쉽독",
  "Belgian Tervuren": "벨기에 터뷰렌",
  Bergamasco: "베르가마스코",
  "Berger Picard": "베르저 피카르",
  "Bernese Mountain Dog": "버니즈 마운틴 독",
  "Bichon Frise": "비숑 프리제",
  "Black and Tan Coonhound": "블랙 앤 탄 쿤하운드",
  "Black Russian Terrie": "블랙 러시안 테리어",
  Bloodhound: "블러드하운드",
  "Blue Picardy Spaniel": "블루 피카르디 스패니얼",
  "Bluetick Coonhound": "블루틱 쿤하운드",
  Boerboel: "보어불",
  Bolognese: "볼로냐즈",
  "Border Collie": "보더 콜리",
  "Border Terrier": "보더 테리어",
  Borzoi: "보르조이",
  "Boston Terrier": "보스턴 테리어",
  "Bouvier des Flandres": "부비에 데 플랑드르",
  Boxer: "복서",
  "Boykin Spaniel": "보이킨 스패니얼",
  "Bracco Italiano": "브라코 이탈리아노",
  Briard: "브리아드",
  Brittany: "브리트니",
  "Brussels Griffon": "브뤼셀 그리펀",
  "Bull Terrier": "불 테리어",
  "Bull Terrier (Miniature)": "미니어처 불 테리어",
  Bulldog: "불독",
  Bullmastiff: "불마스티프",
  "Cairn Terrier": "케언 테리어",
  "Canaan Dog": "카나안 독",
  "Cane Corso": "카네코르소",
  "Cardigan Welsh Corgi": "카디건 웰시 코기",
  "Catahoula Leopard Dog": "카타훌라 리오파드 독",
  "Caucasian Shepherd (Ovcharka)": "코카시안 셰퍼드 (오브차르카)",
  "Cavalier King Charles Spaniel": "캐벌리어 킹 찰스 스패니얼",
  Cavapom: "캐파폼",
  Cavapoo: "캐프푸",
  "Cesky Terrier": "체스키 테리어",
  "Chart Polski": "차트 폴스키",
  "Chesapeake Bay Retriever": "체사피크 베이 리트리버",
  Companionship: "동반자",
  "Chinese Crested": "중국 크레스티드",
  "Chinese Shar-Pei": "중국 샤페이",
  Chinook: "추크",
  "Chow Chow": "차우 차우",
  Chug: "차그",
  "Cirneco dell": "치르네코 델 에트나",
  "Clumber Spaniel": "클럼버 스패니얼",
  Cockapoo: "코커푸",
  "Cocker Spaniel": "코커 스패니얼",
  "Cocker Spaniel (American)": "코커 스패니얼 (아메리칸)",
  Collie: "콜리",
  "Coton de Tulear": "코튼 드 툴레아",
  "Curly-Coated Retriever": "컬리 코티드 리트리버",
  Dachshund: "닥스훈드",
  Dalmatian: "달마티안",
  "Dandie Dinmont Terrier": "덴디 딘몬트 테리어",
  "Doberman Pinscher": "도베르만 핀셔",
  "Dogo Argentino": "도고 아르헨티노",
  "Dogue de Bordeaux": "도그 드 보르도",
  Doxiepoo: "닥스푸",
  "Dutch Shepherd": "더치 쉽허드",
  "English Foxhound": "잉글리쉬 폭스하운드",
  "English Setter": "잉글리쉬 세터",
  "English Shepherd": "잉글리쉬 쉽허드",
  "English Springer Spaniel": "잉글리쉬 스프링어 스패니얼",
  "English Toy Spaniel": "잉글리쉬 토이 스패니얼",
  "English Toy Terrier": "잉글리쉬 토이 테리어",
  "Entlebucher Mountain Dog": "엔틀부허 마운틴 독",
  Eurasier: "유라시어",
  "Field Spaniel": "필드 스패니얼",
  "Fila Brasileiro": "피라 브라질레이로",
  "Finnish Lapphund": "핀란드 랩훈드",
  "Finnish Spitz": "핀란드 스피츠",
  "Flat-Coated Retriever": "플랫코티드 리트리버",
  "French Bulldog": "프렌치 불도그",
  "German Pinscher": "저먼 핀셔",
  "German Shepherd Dog": "저먼 셰퍼드 독",
  "German Shorthaired Pointer": "저먼 숏헤어드 포인터",
  "German Spitz": "저먼 스피츠",
  "German Wirehaired Pointer": "저먼 와이어헤어드 포인터",
  "Giant Schnauzer": "자이언트 스나우저",
  "Glen of Imaal Terrier": "글렌 오브 이맬 테리어",
  "Golden Retriever": "골든 리트리버",
  Goldendoodle: "골덴두들",
  "Gordon Setter": "고든 세터",
  "Great Dane": "그레이트 데인",
  "Great Pyrenees": "그레이트 피레니즈",
  "Greater Swiss Mountain Dog": "그레이터 스위스 마운틴 독",
  Greyhound: "그레이하운드",
  "Griffon Bruxellois": "그리폰 브뤼셀로와",
  Harrier: "해리어",
  Havanese: "하바니즈",
  "Ibizan Hound": "이비잔 하운드",
  "Icelandic Sheepdog": "아이슬란드 쉽독",
  "Irish Red and White Setter": "아이리시 레드 앤 화이트 세터",
  "Irish Setter": "아이리시 세터",
  "Irish Terrier": "아이리시 테리어",
  "Irish Water Spaniel": "아이리시 워터 스패니얼",
  "Irish Wolfhound": "아이리시 울프하운드",
  "Italian Greyhound": "이탈리안 그레이하운드",
  "Jack Russell Terrier": "잭 러셀 테리어",
  "Japanese Chin": "일본 친",
  "Japanese Spitz": "일본 스피츠",
  Keeshond: "키스혼드",
  "Kerry Blue Terrier": "케리 블루 테리어",
  Komondor: "코몬도르",
  Kooikerhondje: "쿠이커혼드",
  Kromfohrlander: "크롬포허랜더",
  Kuvasz: "쿠바스",
  Labradoodle: "라브라도들",
  "Labrador Retriever": "라브라도 리트리버",
  "Lacy Dog": "레이시 독",
  "Lagotto Romagnolo": "라고토 로마뇰로",
  "Lakeland Terrier": "레이클랜드 테리어",
  "Lancashire Heeler": "란카셔 힐러",
  "Large Munsterlander": "라지 먼스터랜더",
  Leonberger: "레온베르거",
  "Lhasa Apso": "라사 압소",
  Lhasapoo: "라사푸",
  Longdog: "롱독",
  Lowchen: "로첸",
  Lurcher: "러처",
  Maltese: "말티즈",
  Maltipoo: "말티푸",
  "Manchester Terrier": "맨체스터 테리어",
  Mastiff: "마스티프",
  "Miniature American Shepherd": "미니어처 아메리칸 셰퍼드",
  "Miniature Bull Terrier": "미니어처 불 테리어",
  "Miniature Pinscher": "미니어처 핀셔",
  "Miniature Schnauzer": "미니어처 슈나우저",
  Mudi: "무디",
  "Neapolitan Mastiff": "나폴리탄 마스티프",
  Newfoundland: "뉴펀들랜드",
  "Norfolk Terrier": "노퍽 테리어",
  "Norwegian Buhund": "노르웨이 부훈드",
  "Norwegian Elkhound": "노르웨이 엘크하운드",
  "Norwegian Lundehund": "노르웨이 룬데훈드",
  "Norwich Terrier": "노리치 테리어",
  "Nova Scotia Duck Tolling Retriever": "노바 스코샤 덕 톨링 리트리버",
  "Old English Sheepdog": "올드 잉글리쉬 숩독",
  "Olde English Bulldogge": "올드 잉글리쉬 불독",
  Otterhound: "오터하운드",
  Papillon: "파피용",
  Pekeapoo: "페키푸",
  Pekingese: "페키니즈",
  "Pembroke Welsh Corgi": "펨브로크 웰시 코기",
  "Perro de Presa Canario": "페로 데 프레사 카나리오",
  "Peruvian Inca Orchid": "페루비안 인카 오키드",
  "Petit Basset Griffon Vendeen": "쁘띠프포 베송 그리펀 반드른",
  "Pharaoh Hound": "파라오 하운드",
  Plott: "플롯",
  Pointer: "포인터",
  "Polish Lowland Sheepdog": "폴리시 로우랜드 쉽독",
  Pomapoo: "포마푸",
  Pomeranian: "포메라니안",
  Pomsky: "폼스키",
  Poodle: "푸들",
  "Poodle (Miniature)": "미니어처 푸들",
  "Poodle (Toy)": "토이 푸들",
  "Portuguese Podengo": "포르투갈리아 포뎅고",
  "Portuguese Water Dog": "포르투갈 워터 독",
  "Presa Canario": "프레사 카나리오",
  Pug: "퍼그",
  Pugapoo: "퍼가푸",
  Puggle: "퍼글",
  Puli: "풀리",
  Pumi: "푸미",
  "Pyrenean Shepherd": "피레네안 셰퍼드",
  "Rat Terrier": "랫 테리어",
  "Redbone Coonhound": "레드본 쿤하운드",
  "Rhodesian Ridgeback": "로데시안 릿지백",
  Rottweiler: "로트와일러",
  "Russian Toy": "러시안 토이",
  "Saint Bernard": "세인트 버나드",
  Saluki: "살루키",
  Samoyed: "사모예드",
  Schapendoes: "샤펜도스",
  Schipperke: "스키퍼키",
  Schnoodle: "슈누들",
  "Scottish Deerhound": "스코티시 디어하운드",
  "Scottish Terrier": "스코티시 테리어",
  "Sealyham Terrier": "실리햄 테리어",
  "Shetland Sheepdog": "셰틀랜드 쉽독",
  "Shiba Inu": "시바 이누",
  "Shih Tzu": "시츄",
  Shihpoo: "시푸",
  "Shiloh Shepherd": "실로 세퍼드",
  "Siberian Husky": "시베리안 허스키",
  "Silken Windhound": "실큰 윈드하운드",
  "Silky Terrier": "실키 테리어",
  "Skye Terrier": "스카이 테리어",
  Sloughi: "슬로우기",
  "Small Munsterlander Pointer": "스몰 문스터랜더 포인터",
  "Smooth Fox Terrier": "스무스 폭스 테리어",
  "Soft Coated Wheaten Terrier": "소프트 코티드 휘튼 테리어",
  "Spanish Greyhound": "스페니쉬 그레이하운드",
  "Spanish Water Dog": "스페니쉬 워터 독",
  "Spinone Italiano": "스피노네 이탈리아노",
  Sprollie: "스프롤리",
  "Staffordshire Bull Terrier": "스태퍼드셔 불 테리어",
  "Standard Schnauzer": "스탠다드 슈나우저",
  "Swedish Lapphund": "스웨디시 랩훈드",
  "Swedish Vallhund": "스웨디시 발훈드",
  "Thai Ridgeback": "타이 리지백",
  "Tibetan Mastiff": "티베탄 매스티프",
  "Tibetan Spaniel": "티베탄 스파니얼",
  "Tibetan Terrier": "티베탄 테리어",
  "Tosa Ken": "토사 켄",
  "Toy Fox Terrier": "토이 폭스 테리어",
  "Toy Poodle": "토이 푸들",
  "Treeing Walker Coonhound": "트리잉 워커 쿤하운드",
  Vizsla: "비즐라",
  "Volpino Italiano": "볼피노 이탈리아노",
  Weimaraner: "와이마라너",
  "Welsh Springer Spaniel": "웰시 스프링거 스패니얼",
  "Welsh Terrier": "웰시 테리어",
  "West Highland White Terrier": "웨스트 하이랜드 화이트 테리어",
  Whippet: "휘펫",
  "White Shepherd": "화이트 세퍼드",
  "Wire Fox Terrier": "와이어 폭스 테리어",
  "Wirehaired Pointing Griffon": "와이어헤어 포인팅 그리펀",
  "Wirehaired Vizsla": "와이어헤어 비즐라",
  Xoloitzcuintli: "쇼로이츠쿠인틀리",
  Yorkipoo: "요크푸",
  "Yorkshire Terrier": "요크셔 테리어",
};

const kornameEngname = {
  아펜핀셔: "Affenpinscher",
  "아프간 하운드": "Afghan Hound",
  "아프리카 혼티드독": "African Hunting Dog",
  "에어데일 테리어": "Airedale Terrier",
  "아크바시 독": "Akbash Dog",
  아키타: "Akita",
  "알라파하 블루 블러드 불독": "Alapaha Blue Blood Bulldog",
  "알래스칸 허스키": "Alaskan Husky",
  "알래스칸 말라뮤트": "Alaskan Malamute",
  "아메리칸 불독": "American Bulldog",
  "아메리칸 불리": "American Bully",
  "아메리칸 에스키모 독": "American Eskimo Dog",
  "미니어처 아메리칸 에스키모 독": "American Eskimo Dog (Miniature)",
  "아메리칸 폭스하운드": "American Foxhound",
  "아메리칸 핏불 테리어": "American Pit Bull Terrier",
  "아메리칸 스태퍼드셔 테리어": "American Staffordshire Terrier",
  "아메리칸 워터 스패니얼": "American Water Spaniel",
  "아나톨리안 세퍼드 독": "Anatolian Shepherd Dog",
  "아펜젤러 세넨훈트": "Appenzeller Sennenhund",
  오시도들: "Aussiedoodle",
  "오스트레일리안 캐틀 독": "Australian Cattle Dog",
  "오스트레일리언 켈피": "Australian Kelpie",
  "오스트레일리언 셰퍼드": "Australian Shepherd",
  "오스트레일리언 테리어": "Australian Terrier",
  아자와크: "Azawakh",
  바베: "Barbet",
  바소더: "Bassador",
  바센지: "Basenji",
  "바세 블루 드 가스코뉴": "Basset Bleu de Gascogne",
  "바세 하운드": "Basset Hound",
  비글: "Beagle",
  "비어디드 콜리": "Bearded Collie",
  보시롱: "Beauceron",
  "베들링턴 테리어": "Bedlington Terrier",
  "벨기에 라이켄와": "Belgian Laekenois",
  "벨기에 말리노이즈": "Belgian Malinois",
  "벨기에 쉽독": "Belgian Sheepdog",
  "벨기에 터뷰렌": "Belgian Tervuren",
  베르가마스코: "Bergamasco",
  "베르저 피카르": "Berger Picard",
  "버니즈 마운틴 독": "Bernese Mountain Dog",
  "비숑 프리제": "Bichon Frise",
  "블랙 앤 탄 쿤하운드": "Black and Tan Coonhound",
  "블랙 러시안 테리어": "Black Russian Terrie",
  블러드하운드: "Bloodhound",
  "블루 피카르디 스패니얼": "Blue Picardy Spaniel",
  "블루틱 쿤하운드": "Bluetick Coonhound",
  보어불: "Boerboel",
  볼로냐즈: "Bolognese",
  "보더 콜리": "Border Collie",
  "보더 테리어": "Border Terrier",
  보르조이: "Borzoi",
  "보스턴 테리어": "Boston Terrier",
  "부비에 데 플랑드르": "Bouvier des Flandres",
  복서: "Boxer",
  "보이킨 스패니얼": "Boykin Spaniel",
  "브라코 이탈리아노": "Bracco Italiano",
  브리아드: "Briard",
  브리트니: "Brittany",
  "브뤼셀 그리펀": "Brussels Griffon",
  "불 테리어": "Bull Terrier",
  "미니어처 불 테리어": "Miniature Bull Terrier",
  불독: "Bulldog",
  불마스티프: "Bullmastiff",
  "케언 테리어": "Cairn Terrier",
  "카나안 독": "Canaan Dog",
  카네코르소: "Cane Corso",
  "카디건 웰시 코기": "Cardigan Welsh Corgi",
  "카타훌라 리오파드 독": "Catahoula Leopard Dog",
  "코카시안 셰퍼드 (오브차르카)": "Caucasian Shepherd (Ovcharka)",
  "캐벌리어 킹 찰스 스패니얼": "Cavalier King Charles Spaniel",
  캐파폼: "Cavapom",
  캐프푸: "Cavapoo",
  "체스키 테리어": "Cesky Terrier",
  "차트 폴스키": "Chart Polski",
  "체사피크 베이 리트리버": "Chesapeake Bay Retriever",
  동반자: "Companionship",
  "중국 크레스티드": "Chinese Crested",
  "중국 샤페이": "Chinese Shar-Pei",
  추크: "Chinook",
  "차우 차우": "Chow Chow",
  차그: "Chug",
  "치르네코 델 에트나": "Cirneco dell",
  "클럼버 스패니얼": "Clumber Spaniel",
  코커푸: "Cockapoo",
  "코커 스패니얼": "Cocker Spaniel",
  "코커 스패니얼 (아메리칸)": "Cocker Spaniel (American)",
  콜리: "Collie",
  "코튼 드 툴레아": "Coton de Tulear",
  "컬리 코티드 리트리버": "Curly-Coated Retriever",
  닥스훈드: "Dachshund",
  달마티안: "Dalmatian",
  "덴디 딘몬트 테리어": "Dandie Dinmont Terrier",
  "도베르만 핀셔": "Doberman Pinscher",
  "도고 아르헨티노": "Dogo Argentino",
  "도그 드 보르도": "Dogue de Bordeaux",
  닥스푸: "Doxiepoo",
  "더치 쉽허드": "Dutch Shepherd",
  "잉글리쉬 폭스하운드": "English Foxhound",
  "잉글리쉬 세터": "English Setter",
  "잉글리쉬 쉽허드": "English Shepherd",
  "잉글리쉬 스프링어 스패니얼": "English Springer Spaniel",
  "잉글리쉬 토이 스패니얼": "English Toy Spaniel",
  "잉글리쉬 토이 테리어": "English Toy Terrier",
  "엔틀부허 마운틴 독": "Entlebucher Mountain Dog",
  유라시어: "Eurasier",
  "필드 스패니얼": "Field Spaniel",
  "피라 브라질레이로": "Fila Brasileiro",
  "핀란드 랩훈드": "Finnish Lapphund",
  "핀란드 스피츠": "Finnish Spitz",
  "플랫코티드 리트리버": "Flat-Coated Retriever",
  "프렌치 불도그": "French Bulldog",
  "저먼 핀셔": "German Pinscher",
  "저먼 셰퍼드 독": "German Shepherd Dog",
  "저먼 숏헤어드 포인터": "German Shorthaired Pointer",
  "저먼 스피츠": "German Spitz",
  "저먼 와이어헤어드 포인터": "German Wirehaired Pointer",
  "자이언트 스나우저": "Giant Schnauzer",
  "글렌 오브 이맬 테리어": "Glen of Imaal Terrier",
  "골든 리트리버": "Golden Retriever",
  골덴두들: "Goldendoodle",
  "고든 세터": "Gordon Setter",
  "그레이트 데인": "Great Dane",
  "그레이트 피레니즈": "Great Pyrenees",
  "그레이터 스위스 마운틴 독": "Greater Swiss Mountain Dog",
  그레이하운드: "Greyhound",
  "그리폰 브뤼셀로와": "Griffon Bruxellois",
  해리어: "Harrier",
  하바니즈: "Havanese",
  "이비잔 하운드": "Ibizan Hound",
  "아이슬란드 쉽독": "Icelandic Sheepdog",
  "아이리시 레드 앤 화이트 세터": "Irish Red and White Setter",
  "아이리시 세터": "Irish Setter",
  "아이리시 테리어": "Irish Terrier",
  "아이리시 워터 스패니얼": "Irish Water Spaniel",
  "아이리시 울프하운드": "Irish Wolfhound",
  "이탈리안 그레이하운드": "Italian Greyhound",
  "잭 러셀 테리어": "Jack Russell Terrier",
  "일본 친": "Japanese Chin",
  "일본 스피츠": "Japanese Spitz",
  키스혼드: "Keeshond",
  "케리 블루 테리어": "Kerry Blue Terrier",
  코몬도르: "Komondor",
  쿠이커혼드: "Kooikerhondje",
  크롬포허랜더: "Kromfohrlander",
  쿠바스: "Kuvasz",
  라브라도들: "Labradoodle",
  "라브라도 리트리버": "Labrador Retriever",
  "레이시 독": "Lacy Dog",
  "라고토 로마뇰로": "Lagotto Romagnolo",
  "레이클랜드 테리어": "Lakeland Terrier",
  "란카셔 힐러": "Lancashire Heeler",
  "라지 먼스터랜더": "Large Munsterlander",
  레온베르거: "Leonberger",
  "라사 압소": "Lhasa Apso",
  라사푸: "Lhasapoo",
  롱독: "Longdog",
  로첸: "Lowchen",
  러처: "Lurcher",
  말티즈: "Maltese",
  말티푸: "Maltipoo",
  "맨체스터 테리어": "Manchester Terrier",
  마스티프: "Mastiff",
  "미니어처 아메리칸 셰퍼드": "Miniature American Shepherd",
  "미니어처 핀셔": "Miniature Pinscher",
  "미니어처 슈나우저": "Miniature Schnauzer",
  무디: "Mudi",
  "나폴리탄 마스티프": "Neapolitan Mastiff",
  뉴펀들랜드: "Newfoundland",
  "노퍽 테리어": "Norfolk Terrier",
  "노르웨이 부훈드": "Norwegian Buhund",
  "노르웨이 엘크하운드": "Norwegian Elkhound",
  "노르웨이 룬데훈드": "Norwegian Lundehund",
  "노리치 테리어": "Norwich Terrier",
  "노바 스코샤 덕 톨링 리트리버": "Nova Scotia Duck Tolling Retriever",
  "올드 잉글리쉬 숩독": "Old English Sheepdog",
  "올드 잉글리쉬 불독": "Olde English Bulldogge",
  오터하운드: "Otterhound",
  파피용: "Papillon",
  페키푸: "Pekeapoo",
  페키니즈: "Pekingese",
  "펨브로크 웰시 코기": "Pembroke Welsh Corgi",
  "페로 데 프레사 카나리오": "Perro de Presa Canario",
  "페루비안 인카 오키드": "Peruvian Inca Orchid",
  "쁘띠프포 베송 그리펀 반드른": "Petit Basset Griffon Vendeen",
  "파라오 하운드": "Pharaoh Hound",
  플롯: "Plott",
  포인터: "Pointer",
  "폴리시 로우랜드 쉽독": "Polish Lowland Sheepdog",
  포마푸: "Pomapoo",
  포메라니안: "Pomeranian",
  폼스키: "Pomsky",
  푸들: "Poodle",
  "미니어처 푸들": "Poodle (Miniature)",
  "토이 푸들": "Toy Poodle",
  "포르투갈리아 포뎅고": "Portuguese Podengo",
  "포르투갈 워터 독": "Portuguese Water Dog",
  "프레사 카나리오": "Presa Canario",
  퍼그: "Pug",
  퍼가푸: "Pugapoo",
  퍼글: "Puggle",
  풀리: "Puli",
  푸미: "Pumi",
  "피레네안 셰퍼드": "Pyrenean Shepherd",
  "랫 테리어": "Rat Terrier",
  "레드본 쿤하운드": "Redbone Coonhound",
  "로데시안 릿지백": "Rhodesian Ridgeback",
  로트와일러: "Rottweiler",
  "러시안 토이": "Russian Toy",
  "세인트 버나드": "Saint Bernard",
  살루키: "Saluki",
  사모예드: "Samoyed",
  샤펜도스: "Schapendoes",
  스키퍼키: "Schipperke",
  슈누들: "Schnoodle",
  "스코티시 디어하운드": "Scottish Deerhound",
  "스코티시 테리어": "Scottish Terrier",
  "실리햄 테리어": "Sealyham Terrier",
  "셰틀랜드 쉽독": "Shetland Sheepdog",
  "시바 이누": "Shiba Inu",
  시츄: "Shih Tzu",
  시푸: "Shihpoo",
  "실로 세퍼드": "Shiloh Shepherd",
  "시베리안 허스키": "Siberian Husky",
  "실큰 윈드하운드": "Silken Windhound",
  "실키 테리어": "Silky Terrier",
  "스카이 테리어": "Skye Terrier",
  슬로우기: "Sloughi",
  "스몰 문스터랜더 포인터": "Small Munsterlander Pointer",
  "스무스 폭스 테리어": "Smooth Fox Terrier",
  "소프트 코티드 휘튼 테리어": "Soft Coated Wheaten Terrier",
  "스페니쉬 그레이하운드": "Spanish Greyhound",
  "스페니쉬 워터 독": "Spanish Water Dog",
  "스피노네 이탈리아노": "Spinone Italiano",
  스프롤리: "Sprollie",
  "스태퍼드셔 불 테리어": "Staffordshire Bull Terrier",
  "스탠다드 슈나우저": "Standard Schnauzer",
  "스웨디시 랩훈드": "Swedish Lapphund",
  "스웨디시 발훈드": "Swedish Vallhund",
  "타이 리지백": "Thai Ridgeback",
  "티베탄 매스티프": "Tibetan Mastiff",
  "티베탄 스파니얼": "Tibetan Spaniel",
  "티베탄 테리어": "Tibetan Terrier",
  "토사 켄": "Tosa Ken",
  "토이 폭스 테리어": "Toy Fox Terrier",
  "트리잉 워커 쿤하운드": "Treeing Walker Coonhound",
  비즐라: "Vizsla",
  "볼피노 이탈리아노": "Volpino Italiano",
  와이마라너: "Weimaraner",
  "웰시 스프링거 스패니얼": "Welsh Springer Spaniel",
  "웰시 테리어": "Welsh Terrier",
  "웨스트 하이랜드 화이트 테리어": "West Highland White Terrier",
  휘펫: "Whippet",
  "화이트 세퍼드": "White Shepherd",
  "와이어 폭스 테리어": "Wire Fox Terrier",
  "와이어헤어 포인팅 그리펀": "Wirehaired Pointing Griffon",
  "와이어헤어 비즐라": "Wirehaired Vizsla",
  쇼로이츠쿠인틀리: "Xoloitzcuintli",
  요크푸: "Yorkipoo",
  "요크셔 테리어": "Yorkshire Terrier",
};

exports.idEngname = idEngname;
exports.idKorname = idKorname;
exports.engnameId = engnameId;
exports.kornameId = kornameId;
exports.engnameKorname = engnameKorname;
exports.kornameEngname = kornameEngname;
